version: "3"
services:
  php:
    build: ./resources/install/php/
    container_name: ghosts-php
    ports:
      - "80:80"
      - "6666:6666"
      - "9003:9003"
    expose:
      - "9000"
    volumes:
      - ./app:/usr/local/app/:rw
      - ./logs/php/:/var/log/php/:rw
      - ./config/php/php.ini:/etc/php.ini:ro
      - ./config/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
    networks:
      - net-php

networks:
  net-php:
